application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /static
  static_dir: static
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application